### PR TITLE
New icon proposal

### PR DESCRIPTION
**Pull request by ragnilorenzo**
Hi, these are the files relating to the new icon proposal we discussed in issue #6 on woeusb-ng branch.

I uploaded both the source code from pixelmator pro and the png export.

I kept the original resolution of 1501x1501 because the files are pretty light; if you need it can scale down to 512x512px or even to a lower resolution.

These files are licensed under GPL v3 

SPDX-License-Identifier: GPL-3.0-or-later
Signed-off-by: Lorenzo Ragni <lorenzo.ragni@outlook.it>

(I hope I didn't make a mess with the pull procedure)

### CODE REVIEW

**Comment by brlin-tw** [comment]
Screenshot_20210222_182512

You appear to be adding empty files, try adding them properly to the commit.

Feel free to close this PR and file a new one, when necessary.

**Comment by WaxyMocha** [comment]
Screenshot_20210222_112739_org mozilla firefox
Looks like it's more of github issue, because you can open them.

**Comment by brlin-tw** [comment]
> Looks like it's more of github issue, because you can open them.

Yep, seems that GitHub is messing with me.  Thanks for the help.

**Comment by WaxyMocha** [comment]
I wanted to ask for .svg first 😛, but ok. Can we agree that for this repository (since it's for both projects), before merging changes we need to have both of us approve a PR?

**Comment by brlin-tw** [comment]
> Can we agree that for this repository (since it's for both projects), before merging changes we need to have both of us approve a PR?

I'm too rushed for approving, apologies.

Let's continue the conversation in the original issue.

**Pull request merged**
